// Mock Companies Data

export const mockCompanies = [
    {
        id: 1,
        name: 'FPT Software',
        email: 'hr@fpt-software.com',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2021/09/Logo-FPT-Polytechnic-V-Dong.png',
        banner: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200',
        taxCode: '0309066388',
        industry: 'Công nghệ thông tin',
        companySize: '1000',
        website: 'https://www.fpt-software.com',
        address: 'Tòa nhà FPT, Đường Tân Thuận, Q.7, TP.HCM',
        phone: '028-3844-3388',
        description: 'FPT Software là công ty phần mềm hàng đầu Việt Nam với hơn 30.000 nhân viên trên toàn cầu. Chuyên cung cấp các giải pháp chuyển đổi số cho doanh nghiệp.',
        benefits: ['Bảo hiểm sức khỏe cao cấp', 'Thưởng hiệu suất hàng quý', 'Du lịch công ty hàng năm', 'Đào tạo nâng cao kỹ năng', 'Làm việc hybrid'],
        isVerified: true,
        verifiedDate: '2025-01-15',
        tier: 'enterprise',
        avatar: 'https://i.pravatar.cc/150?u=company1',
        socialMedia: {
            facebook: 'https://facebook.com/fpt',
            linkedin: 'https://linkedin.com/company/fpt-software',
            twitter: 'https://twitter.com/fpt'
        }
    },
    {
        id: 2,
        name: 'VNG Corporation',
        email: 'recruit@vng.com.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-VNG.png',
        banner: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200',
        taxCode: '0312120782',
        industry: 'Công nghệ - Game',
        companySize: '500',
        website: 'https://www.vng.com.vn',
        address: '182 Lê Đại Hành, P.15, Q.11, TP.HCM',
        phone: '028-3962-0140',
        description: 'VNG là tập đoàn công nghệ hàng đầu Việt Nam, sở hữu Zalo, ZaloPay, Zing MP3 và nhiều sản phẩm game nổi tiếng.',
        benefits: ['Lương thưởng cạnh tranh top 10%', 'Cổ phiếu nhân viên', 'Gym & Yoga miễn phí', 'Game room & giải trí', 'Bữa trưa buffet'],
        isVerified: true,
        verifiedDate: '2025-02-01',
        tier: 'enterprise',
        avatar: 'https://i.pravatar.cc/150?u=company2'
    },
    {
        id: 3,
        name: 'Shopee Vietnam',
        email: 'careers@shopee.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/05/Logo-Shopee.png',
        banner: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200',
        taxCode: '0312370623',
        industry: 'Thương mại điện tử',
        companySize: '1000',
        website: 'https://careers.shopee.vn',
        address: 'Tòa nhà Circo, 222 Điện Biên Phủ, Q.Bình Thạnh, TP.HCM',
        phone: '028-7106-9999',
        description: 'Shopee là nền tảng thương mại điện tử hàng đầu Đông Nam Á, phục vụ hàng triệu người dùng mỗi ngày.',
        benefits: ['Thưởng KPI hấp dẫn', 'Bảo hiểm toàn diện', 'Môi trường quốc tế', 'Team building định kỳ', 'Cơ hội thăng tiến nhanh'],
        isVerified: true,
        verifiedDate: '2025-01-20',
        tier: 'pro',
        avatar: 'https://i.pravatar.cc/150?u=company3'
    },
    {
        id: 4,
        name: 'Tiki Corporation',
        email: 'hr@tiki.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/05/Logo-Tiki.png',
        banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200',
        taxCode: '0315415368',
        industry: 'Thương mại điện tử',
        companySize: '500',
        website: 'https://tiki.vn/careers',
        address: '52 Út Tịch, P.4, Q.Tân Bình, TP.HCM',
        phone: '028-7309-8888',
        description: 'Tiki là nền tảng thương mại điện tử và dịch vụ giao hàng nhanh hàng đầu Việt Nam.',
        benefits: ['Lương tháng 13, 14', 'Review lương 2 lần/năm', 'Chế độ nghỉ phép linh hoạt', 'Khám sức khỏe định kỳ', 'Sách & khóa học miễn phí'],
        isVerified: true,
        verifiedDate: '2025-02-10',
        tier: 'pro',
        avatar: 'https://i.pravatar.cc/150?u=company4'
    },
    {
        id: 5,
        name: 'Viettel Solutions',
        email: 'tuyendung@viettel.com.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-Viettel.png',
        banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200',
        taxCode: '0100109106',
        industry: 'Viễn thông - IT',
        companySize: '1000',
        website: 'https://viettelsolutions.vn',
        address: 'Tầng 5, Tòa nhà Viettel, 285 Cách Mạng Tháng 8, Q.10, TP.HCM',
        phone: '028-3930-0200',
        description: 'Viettel Solutions là đơn vị cung cấp giải pháp công nghệ thông tin hàng đầu, thuộc Tập đoàn Viễn thông Quân đội Viettel.',
        benefits: ['Lương cạnh tranh', 'Chế độ BHXH đầy đủ', 'Thưởng dự án', 'Đào tạo chuyên môn', 'Ổn định lâu dài'],
        isVerified: true,
        verifiedDate: '2025-01-25',
        tier: 'enterprise',
        avatar: 'https://i.pravatar.cc/150?u=company5'
    },
    {
        id: 6,
        name: 'Grab Vietnam',
        email: 'recruitment@grab.com',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-Grab.png',
        banner: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200',
        taxCode: '0313978187',
        industry: 'Công nghệ - Vận tải',
        companySize: '500',
        website: 'https://grab.careers',
        address: 'Lầu 9, Tòa nhà Sài Gòn Centre, 65 Lê Lợi, Q.1, TP.HCM',
        phone: '1900-1877',
        description: 'Grab là siêu ứng dụng hàng đầu Đông Nam Á, cung cấp dịch vụ di chuyển, giao đồ ăn và thanh toán.',
        benefits: ['Lương USD', 'Stock options', 'Bảo hiểm quốc tế', 'Làm việc linh hoạt', 'Văn hóa sáng tạo'],
        isVerified: true,
        verifiedDate: '2025-02-05',
        tier: 'pro',
        avatar: 'https://i.pravatar.cc/150?u=company6'
    },
    {
        id: 7,
        name: 'Momo',
        email: 'jobs@momo.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/10/Logo-MoMo.png',
        banner: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200',
        taxCode: '0312120782',
        industry: 'Fintech',
        companySize: '500',
        website: 'https://momo.vn/careers',
        address: 'Lầu 3, Toà nhà Phước Long, 404-406 Nguyễn Thị Minh Khai, Q.3, TP.HCM',
        phone: '028-7106-8888',
        description: 'MoMo là ví điện tử và nền tảng thanh toán di động hàng đầu Việt Nam với hơn 30 triệu người dùng.',
        benefits: ['Lương thưởng hấp dẫn', 'Cổ phần nhân viên', 'Du lịch nước ngoài', 'Happy hour mỗi tuần', 'Snack & coffee miễn phí'],
        isVerified: true,
        verifiedDate: '2025-02-12',
        tier: 'pro',
        avatar: 'https://i.pravatar.cc/150?u=company7'
    },
    {
        id: 8,
        name: 'VNLife',
        email: 'hr@vnlife.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://ui-avatars.com/api/?name=VNLife&background=4A90E2&color=fff&size=150',
        banner: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200',
        taxCode: '0108888888',
        industry: 'Bảo hiểm - Fintech',
        companySize: '100',
        website: 'https://vnlife.vn',
        address: '123 Lý Tự Trọng, Q.1, TP.HCM',
        phone: '028-3823-5555',
        description: 'VNLife là startup fintech chuyên cung cấp giải pháp bảo hiểm số và quản lý tài chính cá nhân.',
        benefits: ['Startup năng động', 'Equity cho nhân viên xuất sắc', 'Flexible working', 'Học tiếng Anh miễn phí', 'Teambuilding monthly'],
        isVerified: false,
        verifiedDate: null,
        tier: 'basic',
        avatar: 'https://i.pravatar.cc/150?u=company8'
    },
    {
        id: 9,
        name: 'TechViet Solutions',
        email: 'contact@techviet.com',
        password: '123456',
        role: 'employer',
        logo: 'https://ui-avatars.com/api/?name=TechViet&background=FF6B6B&color=fff&size=150',
        banner: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200',
        taxCode: '0109999999',
        industry: 'IT Outsourcing',
        companySize: '100',
        website: 'https://techviet.com',
        address: '45 Nguyễn Văn Cừ, Long Biên, Hà Nội',
        phone: '024-3876-5432',
        description: 'TechViet là công ty outsourcing IT với khách hàng từ Nhật Bản, Hàn Quốc và Singapore.',
        benefits: ['Lương theo năng lực', 'Làm việc với khách hàng quốc tế', 'Đào tạo tiếng Nhật', 'Cơ hội onsite', 'BHYT bổ sung'],
        isVerified: true,
        verifiedDate: '2025-03-01',
        tier: 'basic',
        avatar: 'https://i.pravatar.cc/150?u=company9'
    },
    {
        id: 10,
        name: 'Ngân hàng ACB',
        email: 'hr@acb.com.vn',
        password: '123456',
        role: 'employer',
        logo: 'https://cdn.haitrieu.com/wp-content/uploads/2022/02/Logo-ACB.png',
        banner: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=1200',
        taxCode: '0303030303',
        industry: 'Ngân hàng',
        companySize: '1000',
        website: 'https://acb.com.vn/careers',
        address: '442 Nguyễn Thị Minh Khai, Q.3, TP.HCM',
        phone: '1900-545-441',
        description: 'ACB là một trong những ngân hàng thương mại cổ phần hàng đầu Việt Nam với mạng lưới chi nhánh rộng khắp.',
        benefits: ['Lương cứng + KPI', 'Thưởng theo hiệu quả', 'BHXH, BHYT đầy đủ', 'Đào tạo bài bản', 'Môi trường chuyên nghiệp'],
        isVerified: true,
        verifiedDate: '2025-01-10',
        tier: 'enterprise',
        avatar: 'https://i.pravatar.cc/150?u=company10'
    }
];
